//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMODOC_DETT
    {
        public string MVSERIAL { get; set; }
        public int CPROWNUM { get; set; }
        public Nullable<int> CPROWORD { get; set; }
        public int MVNUMRIF { get; set; }
        public string MVCODICE { get; set; }
        public string MVTIPRIG { get; set; }
        public string MVDESART { get; set; }
        public string MVCODART { get; set; }
        public string MVUNIMIS { get; set; }
        public string MVCATCON { get; set; }
        public string MVDESSUP { get; set; }
        public string MVCONIND { get; set; }
        public string MVCAUMAG { get; set; }
        public string MVCONTRO { get; set; }
        public string MVCAUCOL { get; set; }
        public string MVCODMAG { get; set; }
        public string MVCODMAT { get; set; }
        public string MVCODCLA { get; set; }
        public string MVCODLIS { get; set; }
        public Nullable<decimal> MVQTAMOV { get; set; }
        public Nullable<decimal> MVQTAUM1 { get; set; }
        public Nullable<decimal> MVPREZZO { get; set; }
        public Nullable<decimal> MVSCONT1 { get; set; }
        public Nullable<decimal> MVSCONT2 { get; set; }
        public Nullable<decimal> MVSCONT3 { get; set; }
        public Nullable<decimal> MVSCONT4 { get; set; }
        public string MVFLOMAG { get; set; }
        public string MVCODIVA { get; set; }
        public Nullable<decimal> MVVALRIG { get; set; }
        public Nullable<decimal> MVIMPACC { get; set; }
        public string MVCONTRA { get; set; }
        public Nullable<decimal> MVVALMAG { get; set; }
        public Nullable<decimal> MVIMPNAZ { get; set; }
        public Nullable<decimal> MVIMPSCO { get; set; }
        public string MVFLCASC { get; set; }
        public string MVF2CASC { get; set; }
        public string MVKEYSAL { get; set; }
        public string MVF2ORDI { get; set; }
        public string MVFLORDI { get; set; }
        public string MVF2IMPE { get; set; }
        public string MVFLIMPE { get; set; }
        public string MVF2RISE { get; set; }
        public string MVFLRISE { get; set; }
        public Nullable<decimal> MVPERPRO { get; set; }
        public Nullable<decimal> MVIMPPRO { get; set; }
        public Nullable<decimal> MVPESNET { get; set; }
        public string MVFLTRAS { get; set; }
        public string MVNOMENC { get; set; }
        public string MVUMSUPP { get; set; }
        public string MVNAZPRO { get; set; }
        public Nullable<decimal> MVMOLSUP { get; set; }
        public string MVPROORD { get; set; }
        public Nullable<int> MVNUMCOL { get; set; }
        public string MVTIPCOL { get; set; }
        public string MVCODCOM { get; set; }
        public Nullable<decimal> MVQTAEVA { get; set; }
        public Nullable<decimal> MVQTAEV1 { get; set; }
        public string MVFLRAGG { get; set; }
        public Nullable<decimal> MVIMPEVA { get; set; }
        public Nullable<decimal> MVQTASAL { get; set; }
        public Nullable<System.DateTime> MVEFFEVA { get; set; }
        public Nullable<System.DateTime> MVDATEVA { get; set; }
        public string MVFLELGM { get; set; }
        public string MVFLEVAS { get; set; }
        public Nullable<int> MVROWRIF { get; set; }
        public string MVSERRIF { get; set; }
        public Nullable<decimal> MVQTANOC { get; set; }
        public string MVFLARIF { get; set; }
        public string MVFLRESC { get; set; }
        public string MVFLERIF { get; set; }
        public string MVTIPATT { get; set; }
        public Nullable<decimal> MVQTARES { get; set; }
        public string MVCODCOS { get; set; }
        public string MVFLRIAP { get; set; }
        public Nullable<decimal> MVPRECON { get; set; }
        public string MVFLORCO { get; set; }
        public string MVFLCOCO { get; set; }
        public string MVFLULPV { get; set; }
        public string MVFLULCA { get; set; }
        public Nullable<decimal> MVIMPCOM { get; set; }
        public Nullable<decimal> MVVALULT { get; set; }
        public Nullable<System.DateTime> MVINICOM { get; set; }
        public Nullable<System.DateTime> MVDATGEN { get; set; }
        public Nullable<System.DateTime> MVFINCOM { get; set; }
        public string MVRIFORD { get; set; }
        public string MVCODATT { get; set; }
        public string MVCODCEN { get; set; }
        public string MVCODODL { get; set; }
        public string MVVOCCEN { get; set; }
        public string MVCODCOL { get; set; }
        public string MVFLRIPA { get; set; }
        public Nullable<decimal> MVIMPRBA { get; set; }
        public string MVFLELAN { get; set; }
        public string MVRIFESC { get; set; }
        public Nullable<int> MVRIGMAT { get; set; }
        public string MVF2LOTT { get; set; }
        public string MVFLLOTT { get; set; }
        public string MVCODLOT { get; set; }
        public string MVCODUB2 { get; set; }
        public string MV_FLAGG { get; set; }
        public string MVFLRVCL { get; set; }
        public string MVCODUBI { get; set; }
        public Nullable<decimal> MVQTAIM1 { get; set; }
        public string MVTIPPRO { get; set; }
        public string MV_SEGNO { get; set; }
        public string MVCODCES { get; set; }
        public string MVCESSER { get; set; }
        public Nullable<decimal> MVQTAIMP { get; set; }
        public Nullable<decimal> MVIMPAC2 { get; set; }
        public string MVUNILOG { get; set; }
        public Nullable<decimal> MVPROCAP { get; set; }
        public Nullable<decimal> MVIMPCAP { get; set; }
        public string MVTIPPR2 { get; set; }
        public string MVFLNOAN { get; set; }
        public string MVMC_PER { get; set; }
        public Nullable<System.DateTime> MVDATOAI { get; set; }
        public Nullable<System.DateTime> MVDATOAF { get; set; }
        public string MVPAEFOR { get; set; }
        public string MVAIRPOR { get; set; }
        public string MVRIFEDI { get; set; }
        public string MVCODRES { get; set; }
        public Nullable<int> MVRIFCAC { get; set; }
        public string MVCACONT { get; set; }
        public string MVLOTMAG { get; set; }
        public string MVLOTMAT { get; set; }
        public Nullable<int> MVRIFPRE { get; set; }
        public string MVRIGPRE { get; set; }
        public Nullable<int> MVROWWEB { get; set; }
        public string cpccchk { get; set; }
    
        public virtual DEMODOC_MAST DEMODOC_MAST { get; set; }
    }
}
