//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMODOC_MAST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEMODOC_MAST()
        {
            this.DEMODOC_DETT = new HashSet<DEMODOC_DETT>();
        }
    
        public string MVSERIAL { get; set; }
        public Nullable<int> MVCODUTE { get; set; }
        public Nullable<decimal> MVNUMREG { get; set; }
        public Nullable<System.DateTime> MVDATREG { get; set; }
        public Nullable<System.DateTime> MVDATPLA { get; set; }
        public string MVTIPDOC { get; set; }
        public string MVCLADOC { get; set; }
        public string MVFLVEAC { get; set; }
        public string MVFLACCO { get; set; }
        public string MVFLINTE { get; set; }
        public string MVFLPROV { get; set; }
        public string MVPRD { get; set; }
        public string MVCODESE { get; set; }
        public string MVPRP { get; set; }
        public Nullable<decimal> MVNUMDOC { get; set; }
        public string MVALFDOC { get; set; }
        public Nullable<System.DateTime> MVDATDOC { get; set; }
        public string MVANNDOC { get; set; }
        public string MVANNPRO { get; set; }
        public Nullable<decimal> MVNUMEST { get; set; }
        public string MVALFEST { get; set; }
        public Nullable<System.DateTime> MVDATEST { get; set; }
        public Nullable<System.DateTime> MVDATCIV { get; set; }
        public string MVTCAMAG { get; set; }
        public string MVTCONTR { get; set; }
        public string MVTCOLIS { get; set; }
        public string MVTFRAGG { get; set; }
        public string MVCAUCON { get; set; }
        public string MVTIPCON { get; set; }
        public string MVCODCON { get; set; }
        public string MVCODDES { get; set; }
        public string MVCODAGE { get; set; }
        public string MVCODPAG { get; set; }
        public Nullable<System.DateTime> MVDATDIV { get; set; }
        public string MVCODAG2 { get; set; }
        public string MVCODBAN { get; set; }
        public string MVCODBA2 { get; set; }
        public string MVVALNAZ { get; set; }
        public string MVCODVAL { get; set; }
        public Nullable<decimal> MVCAOVAL { get; set; }
        public Nullable<decimal> MVSCOCL1 { get; set; }
        public Nullable<decimal> MVSCOCL2 { get; set; }
        public Nullable<decimal> MVSCOPAG { get; set; }
        public string MVCODIVE { get; set; }
        public string MVRIFDIC { get; set; }
        public string MVFLSCOR { get; set; }
        public string MVFLGIOM { get; set; }
        public Nullable<System.DateTime> MVTINCOM { get; set; }
        public Nullable<System.DateTime> MVTFICOM { get; set; }
        public string MVTIPOPE { get; set; }
        public string MVCATOPE { get; set; }
        public string MVFLFOSC { get; set; }
        public Nullable<decimal> MVSCONTI { get; set; }
        public string MVIVAINC { get; set; }
        public string MVFLRINC { get; set; }
        public string MVIVATRA { get; set; }
        public Nullable<decimal> MVSPEBOL { get; set; }
        public Nullable<decimal> MVSPETRA { get; set; }
        public string MVIVAARR { get; set; }
        public string MVIVAIMB { get; set; }
        public string MVFLRTRA { get; set; }
        public string MVIVABOL { get; set; }
        public Nullable<decimal> MVIMPARR { get; set; }
        public Nullable<decimal> MVACCPRE { get; set; }
        public Nullable<decimal> MVTOTRIT { get; set; }
        public Nullable<int> MVMAXACC { get; set; }
        public string MVFLRIMB { get; set; }
        public string MVCODVET { get; set; }
        public Nullable<decimal> MVSPEIMB { get; set; }
        public Nullable<decimal> MVACCSUC { get; set; }
        public Nullable<decimal> MVTOTENA { get; set; }
        public string MVCODVE3 { get; set; }
        public string MVCODVE2 { get; set; }
        public Nullable<decimal> MVSPEINC { get; set; }
        public string MVCONCON { get; set; }
        public string MVCODPOR { get; set; }
        public Nullable<int> MVQTACOL { get; set; }
        public string MVASPEST { get; set; }
        public string MVCODSPE { get; set; }
        public Nullable<decimal> MVQTAPES { get; set; }
        public string MVCODORN { get; set; }
        public string MVNOTAGG { get; set; }
        public Nullable<decimal> MVQTALOR { get; set; }
        public string MVGENEFF { get; set; }
        public string MVTIPORN { get; set; }
        public string MVGENPRO { get; set; }
        public Nullable<decimal> MVACCONT { get; set; }
        public string MVRIFPIA { get; set; }
        public string MVRIFCON { get; set; }
        public string MVMINTRA { get; set; }
        public string MVFLCONT { get; set; }
        public Nullable<int> UTCC { get; set; }
        public Nullable<System.DateTime> UTDV { get; set; }
        public string MVRIFACC { get; set; }
        public Nullable<System.DateTime> MVDATTRA { get; set; }
        public string MVACIVA5 { get; set; }
        public Nullable<int> UTCV { get; set; }
        public string MVACIVA1 { get; set; }
        public string MVORATRA { get; set; }
        public string MVACIVA3 { get; set; }
        public string MVACIVA4 { get; set; }
        public string MVACIVA2 { get; set; }
        public string MVRIFFAD { get; set; }
        public Nullable<decimal> MVAIMPN1 { get; set; }
        public string MVACIVA6 { get; set; }
        public Nullable<System.DateTime> UTDC { get; set; }
        public Nullable<decimal> MVAIMPN5 { get; set; }
        public Nullable<decimal> MVAIMPN6 { get; set; }
        public Nullable<decimal> MVAIMPN2 { get; set; }
        public Nullable<decimal> MVAIMPN3 { get; set; }
        public Nullable<decimal> MVAIMPS6 { get; set; }
        public Nullable<decimal> MVAIMPN4 { get; set; }
        public Nullable<decimal> MVAIMPS4 { get; set; }
        public Nullable<decimal> MVAIMPS3 { get; set; }
        public Nullable<decimal> MVAIMPS2 { get; set; }
        public Nullable<decimal> MVAIMPS5 { get; set; }
        public string MVAFLOM1 { get; set; }
        public string MVAFLOM2 { get; set; }
        public string MVAFLOM4 { get; set; }
        public string MVAFLOM6 { get; set; }
        public string MVAFLOM3 { get; set; }
        public Nullable<decimal> MVAIMPS1 { get; set; }
        public string MVAFLOM5 { get; set; }
        public string MVANNRET { get; set; }
        public string MVTIPPER { get; set; }
        public Nullable<int> MVPERRET { get; set; }
        public string MVCODASP { get; set; }
        public Nullable<decimal> MVTRAINT { get; set; }
        public string MV__NOTE { get; set; }
        public string MVFLINTR { get; set; }
        public string MVFLSALD { get; set; }
        public string MVFLCAPA { get; set; }
        public string MVFLSCAF { get; set; }
        public string MVRIFESP { get; set; }
        public string MVMOVCOM { get; set; }
        public string MVRIFODL { get; set; }
        public string MVRIFDCO { get; set; }
        public string MVFLBLOC { get; set; }
        public string MVSERDDT { get; set; }
        public Nullable<int> MVROWDDT { get; set; }
        public string MVDESDOC { get; set; }
        public string MVFLOFFE { get; set; }
        public string MVCODSED { get; set; }
        public string MVFLVABD { get; set; }
        public Nullable<decimal> MVACCOLD { get; set; }
        public string MVNUMCOR { get; set; }
        public string MVSERWEB { get; set; }
        public Nullable<decimal> MVRITPRE { get; set; }
        public Nullable<decimal> MVPERFIN { get; set; }
        public Nullable<decimal> MVIMPFIN { get; set; }
        public string MVFLSFIN { get; set; }
        public string MVFLSCOM { get; set; }
        public Nullable<decimal> MVCAUIMB { get; set; }
        public string MVIVACAU { get; set; }
        public Nullable<decimal> MVRITATT { get; set; }
        public string MVFLFOCA { get; set; }
        public string MVTIPIMB { get; set; }
        public string MVSEREST { get; set; }
        public string MVFLSEND { get; set; }
        public Nullable<int> MV__ANNO { get; set; }
        public Nullable<int> MV__MESE { get; set; }
        public string MVTIPDIS { get; set; }
        public Nullable<bool> MVGENPOS { get; set; }
        public string MVSTFILCB { get; set; }
        public string MVFLGINC { get; set; }
        public string MVEMERIC { get; set; }
        public string MVAGG_01 { get; set; }
        public string MVAGG_02 { get; set; }
        public string MVAGG_03 { get; set; }
        public string MVAGG_04 { get; set; }
        public Nullable<System.DateTime> MVAGG_05 { get; set; }
        public Nullable<System.DateTime> MVAGG_06 { get; set; }
        public string MVRIFPRO { get; set; }
        public string MVGENPRE { get; set; }
        public string MVRIFEST { get; set; }
        public string cpccchk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEMODOC_DETT> DEMODOC_DETT { get; set; }
        public virtual DEMOTIP_DOCU DEMOTIP_DOCU { get; set; }
    }
}
