//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMOTIP_DOCU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEMOTIP_DOCU()
        {
            this.DEMODOC_MAST = new HashSet<DEMODOC_MAST>();
        }
    
        public string TDTIPDOC { get; set; }
        public string TDDESDOC { get; set; }
        public string TDCATDOC { get; set; }
        public string TDFLVEAC { get; set; }
        public string TDFLINTE { get; set; }
        public string TDPRODOC { get; set; }
        public string TDALFDOC { get; set; }
        public string TDSERPRO { get; set; }
        public string TDFLPPRO { get; set; }
        public string TDCAUCON { get; set; }
        public string TDCAUMAG { get; set; }
        public string TDCODMAG { get; set; }
        public string TDCODMAT { get; set; }
        public Nullable<int> TDPRGSTA { get; set; }
        public string TDFLACCO { get; set; }
        public string TFFLGEFA { get; set; }
        public string TFFLRAGG { get; set; }
        public string TDFLRICE { get; set; }
        public string TDFLCASH { get; set; }
        public string TDFLRISC { get; set; }
        public string TDFLCRIS { get; set; }
        public string TDFLNSRI { get; set; }
        public string TDFLVSRI { get; set; }
        public string TDFLDATT { get; set; }
        public string TDFLORAT { get; set; }
        public string TDFLPROV { get; set; }
        public string TDFLDTPR { get; set; }
        public string TDFLNSTA { get; set; }
        public string TDFLIMPA { get; set; }
        public string TDFLIMAC { get; set; }
        public string TDFLPACK { get; set; }
        public string TDASPETT { get; set; }
        public Nullable<int> TDNUMSCO { get; set; }
        public string TDSTACL1 { get; set; }
        public string TDSTACL2 { get; set; }
        public string TDSTACL3 { get; set; }
        public string TDSTACL4 { get; set; }
        public string TDSTACL5 { get; set; }
        public string TDESCCL1 { get; set; }
        public string TDESCCL2 { get; set; }
        public string TDESCCL3 { get; set; }
        public string TDESCCL4 { get; set; }
        public string TDESCCL5 { get; set; }
        public string TDTPNDOC { get; set; }
        public string TDTPVDOC { get; set; }
        public string TDSEQPRE { get; set; }
        public string TDSEQSCO { get; set; }
        public string TDSEQMA1 { get; set; }
        public string TDSEQMA2 { get; set; }
        public string TDNOPRSC { get; set; }
        public string TDFLPREF { get; set; }
        public string TDCODLIS { get; set; }
        public Nullable<decimal> TDQTADEF { get; set; }
        public string TDEMERIC { get; set; }
        public string TDFLANAL { get; set; }
        public string TDFLCOMM { get; set; }
        public string TDFLSILI { get; set; }
        public string TDFLELAN { get; set; }
        public string TDFLARCO { get; set; }
        public string TDCAUPFI { get; set; }
        public string TDCAUCOD { get; set; }
        public string TDFLPDOC { get; set; }
        public string TDFLEXPL { get; set; }
        public Nullable<int> TDPROSTA { get; set; }
        public string TDFLRIDE { get; set; }
        public string TDTPRDES { get; set; }
        public string TDDESRIF { get; set; }
        public string TDEXPAUT { get; set; }
        public string TDFLESPF { get; set; }
        public string TDFLMGPR { get; set; }
        public string TDFLMTPR { get; set; }
        public string TDVOCECR { get; set; }
        public string TD_SEGNO { get; set; }
        public string TDPRZVAC { get; set; }
        public string TDASSCES { get; set; }
        public string TDCAUCES { get; set; }
        public string TDFLVALO { get; set; }
        public string TDPRZDES { get; set; }
        public string TDFLSTLM { get; set; }
        public Nullable<int> TDPROALT { get; set; }
        public Nullable<int> TDSINCFL { get; set; }
        public string TDVALCOM { get; set; }
        public string TDBOLDOG { get; set; }
        public string TDFLCCAU { get; set; }
        public string TDFLQRIO { get; set; }
        public string TDFLPREV { get; set; }
        public string TDCHKTOT { get; set; }
        public string TDFLSPTR { get; set; }
        public string TDFLSPIM { get; set; }
        public string TDMCALST { get; set; }
        public string TDMCALSI { get; set; }
        public string TDFLBLEV { get; set; }
        public string TDFLSCOR { get; set; }
        public Nullable<int> TDMAXLEV { get; set; }
        public string TDFLRIFI { get; set; }
        public string TDLOTDIF { get; set; }
        public string TDCONASS { get; set; }
        public string TDFLSPIN { get; set; }
        public string TDMODRIF { get; set; }
        public string TDTIPIMB { get; set; }
        public string TDCODSTR { get; set; }
        public string TDFLRIAT { get; set; }
        public string TDRIPINC { get; set; }
        public string TDRIPIMB { get; set; }
        public string TDRIPTRA { get; set; }
        public string TDORDAPE { get; set; }
        public string TDMTDCLC { get; set; }
        public string TDFLBACA { get; set; }
        public string TDFLPRAT { get; set; }
        public string TDMINVAL { get; set; }
        public Nullable<decimal> TDMINIMP { get; set; }
        public string TDFLAPCA { get; set; }
        public string TDRICNOM { get; set; }
        public string TDCOSEPL { get; set; }
        public string TDRIPCON { get; set; }
        public string TDNOSTCO { get; set; }
        public string TDFLGETR { get; set; }
        public string TDFLGLIS { get; set; }
        public string TDFLRIPS { get; set; }
        public string TDFLATIP { get; set; }
        public string TDFLGCHI { get; set; }
        public string TDFLNORC { get; set; }
        public string TDCHKUCA { get; set; }
        public string TDMODDES { get; set; }
        public string TDFLIA01 { get; set; }
        public string TDFLIA02 { get; set; }
        public string TDFLIA03 { get; set; }
        public string TDFLIA04 { get; set; }
        public string TDFLIA05 { get; set; }
        public string TDFLIA06 { get; set; }
        public string TDFLRA01 { get; set; }
        public string TDFLRA02 { get; set; }
        public string TDFLRA03 { get; set; }
        public string TDFLRA04 { get; set; }
        public string TDFLRA05 { get; set; }
        public string TDFLRA06 { get; set; }
        public string TDTOTDOC { get; set; }
        public Nullable<decimal> TDIMPMIN { get; set; }
        public string TDIVAMIN { get; set; }
        public string TDMINVEN { get; set; }
        public string TDRIOTOT { get; set; }
        public string TDPROVVI { get; set; }
        public string TDCONFIG { get; set; }
        public Nullable<int> UTCC { get; set; }
        public Nullable<int> UTCV { get; set; }
        public Nullable<System.DateTime> UTDC { get; set; }
        public Nullable<System.DateTime> UTDV { get; set; }
        public string cpccchk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEMODOC_MAST> DEMODOC_MAST { get; set; }
    }
}
