//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WideWorldImportEntities : DbContext
    {
        public WideWorldImportEntities()
            : base("name=WideWorldImportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AZIENDA> AZIENDA { get; set; }
        public virtual DbSet<DEMODOC_DETT> DEMODOC_DETT { get; set; }
        public virtual DbSet<DEMODOC_MAST> DEMODOC_MAST { get; set; }
        public virtual DbSet<DEMODOCSDETT> DEMODOCSDETT { get; set; }
        public virtual DbSet<DEMODOCSMAST> DEMODOCSMAST { get; set; }
        public virtual DbSet<DEMOTIP_DOCU> DEMOTIP_DOCU { get; set; }
    }
}
